### ISSUE TITLE
详细信息：本站已关闭重置密码功能

### ISSUE THREAD

**Issue by sintaxcz** [printempw/blessing-skin-server#30] opened 2016-08-24 19:37 UTC
出现了一些错误：

错误码： 8

详细信息：本站已关闭重置密码功能

Hello i have this problem i think its mean i dont have allowed password resseting but i cant find where is  function to enable password reseting
 (im from czech republic sry for my bad english)

Sry im retarded now i see setings in .env

**Comment by prinsss** [comment] 2016-08-25 00:01
Well, seriously, I wasn't expecting that there are users from other countries. Is there a common need of skin servers in your country?

**Comment by sintaxcz** [comment] 2016-08-25 01:25
yes in some cases like mine server running on Thermos 1.7.10 (Cauldrons etc.)with mods in offline mode we have problems with skins (spigot plugins like SkinsRestorer doesnt work correctly: players see own skin look like steve and only others see theyr skins ) that is not acceptable. I looks every where to find acceptable solution for this problem and after realy long searching  on web i found this (yes long long serching becouse chinese language is not on front pages for me) and this skin server is realy ammazing and i love it and only thing i need is VPS with WampServer installed and thats it.

Best thing is i manage to succesfully instal this even in Chinese lang + edit config of CustomSkinLoader mod and it is working i have my own custom skin on my minecraft server without problems !

Thans to google translator from Chinese ->Czech i manage translate 75% of it (at this moment I make 100% tomorrow) 
I know google translator is not 100% correct but this is only way for me and i correcting every world one by one and everything going great.

Thanks for making this amazing project !!

**Comment by Minecraft-LittleQiu** [comment] 2016-08-25 03:16
Prelozen googlem
Nesmíte muset vyplnit údaje SMTP serveru v souboru .env
Pokud nevyplníte, nebude server odeslat resetování hesla e-mailem na vás.
Můžete použít Gmail nebo Outlook, které podporují SMTP.
Případně můžete použít můj SMTP službu, vyplňte následující informace v .env souboru:
MAIL_HOST = "smtp.mxhichina.com"
MAIL_PORT = 25
MAIL_USERNAME = "mcskin@littleservice.cn"
MAIL_PASSWORD = "LittleService2333"
MAIL_ENCRYPTION = "tls"

**Comment by Minecraft-LittleQiu** [comment] 2016-08-25 03:24
Translation by Baidu
You may not fill in the SMTP server information in the .env file.
If you do not fill in, the site will not be able to send you a password reset message.
You can use Gmail or Outlook, they support SMTP. Related information, please search on Google or Bing.

**Comment by prinsss** [comment] 2016-08-25 03:35
Wow that's awesome!
Internationalization of the project is in the plan.

Language file in english will be given in the future, and translation will be much more convenient :)

**Comment by sintaxcz** [comment] 2016-08-25 03:54
I heve few things to aks you : 
What is minimum VPS configuration for this proect ? I have 4 gb ram 1x xenon 1.7 ghz core
 and some times i feel website reactions being slow 
then sometimes avatars or skin pictures doesnt load 
When i set Avatar from the skin notting happens still have Steve Avatar
Sometimes i when i select link from left menu (switching form closet to skin library etc.) i got Woops! error and after F5 site is loaded without problem
And finaly where to find content for popup windows (like when i login that message with green symbol anination you loget in sucessfuly etc.) and where to find content of small popups that appears on right (those with i symbol)

**Comment by prinsss** [comment] 2016-08-25 04:12
The required vps configuration is not high, and yours is actually enough. Even the demo site is deployed on a 1 Core 512M RAM vps.

The slow reactions may be the problem caused by the code. And optimization of performance is which I need to do in the future.

**Comment by g-plane** [comment] 2016-08-25 04:15
You cannot see avatar. Do you use nginx web server?

**Comment by prinsss** [comment] 2016-08-25 04:18
The content of popup windows and toast notifications is defined in JavaScript files which located in /assets/dist/js.

But the js files in dist folder in compressed, which are suck. So it's better to download files in /assets/src/js from github, which is not compressed.

Just download these files and replace them into the /assets/dist/js folder, and it will work as fine as compressed ones.

https://github.com/printempw/blessing-skin-server/tree/master/assets/src/js

**Comment by sintaxcz** [comment] 2016-08-25 04:25
Ok thanks for info on popups and toast.
Issue with avatar no i dont use Nginx becouse its not working right on MS Windows server 2012 with those rewrite rulles in readme (nginx dont work well on windows anyway)
I use WampServer3 its easyest one click Apache+Php+Mysql suporting czech laguage ;)
Without Nginx i cant change avatars ?

**Comment by prinsss** [comment] 2016-08-25 04:29
As for the avatar problem, there was a user having the same problem. Could you offer the detailed informations of the error exceptions such as error message, file name and lines?

**Comment by prinsss** [comment] 2016-08-25 04:31
Nop, it's not nginx who causes the problem. To find the actual reason, detailed error messages is required.

**Comment by prinsss** [comment] 2016-08-25 04:38
Ah..well, actually, the message like "Login Successfully" is defined in files located in app/Controllers. The text in the JavaScript files is just notice for validation.

For example, messages of authentication is defined in app/Controllers/AuthController.php, which will be returned to client for showing through an Ajax request.

**Comment by sintaxcz** [comment] 2016-09-05 23:38
Hello i have manage translate (i hope) all user area by 100% but im on 3.0.3 and i have a problem i got errors lots of them looks like that (that is not related to translation i got these errors in chinese)
![all the time](https://cloud.githubusercontent.com/assets/20709982/18258230/110eb9d0-73d2-11e6-86f0-22f585a3838e.png)

Environment & details:

GET Data
tid 4
POST Data empty
Files empty
Cookies
_ga GA1.2.909189330.1468784719
PHPSESSID   hh4no2lqkhd927tbeip8s2qm51
uid 1
token   8154d62fe0ddf5bbe7dec1c60ffebd4b
Session empty
Server/Request Data
REDIRECT_STATUS 200
HTTP_HOST   skin.megamodded.cz
HTTP_CONNECTION keep-alive
HTTP_UPGRADE_INSECURE_REQUESTS  1
HTTP_USER_AGENT Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
HTTP_ACCEPT text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
HTTP_REFERER    http://skin.megamodded.cz/user/closet
HTTP_ACCEPT_ENCODING    gzip, deflate, sdch
HTTP_ACCEPT_LANGUAGE    cs-CZ,cs;q=0.8
HTTP_COOKIE _ga=GA1.2.909189330.1468784719; PHPSESSID=hh4no2lqkhd927tbeip8s2qm51; uid=1; token=8154d62fe0ddf5bbe7dec1c60ffebd4b
PATH    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
SystemRoot  C:\Windows
COMSPEC C:\Windows\system32\cmd.exe
PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
WINDIR  C:\Windows
SERVER_SIGNATURE  
Apache/2.4.18 (Win64) PHP/5.6.19 Server at skin.megamodded.cz Port 80
SERVER_SOFTWARE Apache/2.4.18 (Win64) PHP/5.6.19
SERVER_NAME skin.megamodded.cz
SERVER_ADDR 37.157.193.215
SERVER_PORT 80
REMOTE_ADDR 78.102.95.169
DOCUMENT_ROOT   C:/wamp64/www
REQUEST_SCHEME  http
CONTEXT_PREFIX  
CONTEXT_DOCUMENT_ROOT   C:/wamp64/www
SERVER_ADMIN    admin@example.com
SCRIPT_FILENAME C:/wamp64/www/index.php
REMOTE_PORT 56785
REDIRECT_URL    /skinlib/show
REDIRECT_QUERY_STRING   tid=4
GATEWAY_INTERFACE   CGI/1.1
SERVER_PROTOCOL HTTP/1.1
REQUEST_METHOD  GET
QUERY_STRING    tid=4
REQUEST_URI /skinlib/show?tid=4
SCRIPT_NAME /index.php
PHP_SELF    /index.php
REQUEST_TIME_FLOAT  1473118264.986
REQUEST_TIME    1473118264
Environment Variables empty
Registered Handlers
0. Whoops\Handler\PrettyPageHandler

+Avatars doesnt work (i have only steave head or blank picture and skin filesin closet  sometimes are blank)

**Comment by prinsss** [comment] 2016-09-06 09:40
I think this is the reason why avatars & skin previews dosen't work.

I don't know why the DB_HOST index doesn't exist in `$_ENV`, since putenv is available, but it just be. May it is caused by different system environment.

There is a temporary solution:
Fill your database configuration into file `config/database.php` to replace ones like this `$_ENV['DB_HOST']`, so that configurations in file `.env` is not so necessary.

**Comment by sintaxcz** [comment] 2016-09-06 10:07
Ok filled in config/database.php - avatars & skin previews dosen't work.
and new error appears
![error](https://cloud.githubusercontent.com/assets/20709982/18269880/6c9e5a28-742a-11e6-9d1d-547596e611ca.png)

looks like everythin connected to .env = errored

edit: Ok i fill this salt .etc in user.php looks like errors gone but still avatars & skin previews dosen't work.
i must hit F5 manny times to see skin preview

**Comment by sintaxcz** [comment] 2016-09-06 10:43
Closet looks like that

![empty closet](https://cloud.githubusercontent.com/assets/20709982/18270829/3bb75838-742f-11e6-86bb-8956d0db3753.png)

After random times hit F5 avatar (steave head becouse seting avatar from skin fille do nothing)
and skin appears normal but after another F5 or switching to dashboard (or annywhere) and back to closet imgages dissapers again :(

**Comment by prinsss** [comment] 2016-09-07 04:59
Right click on the broken images and open them in a new tab, then hit F5. 
There should be some detailed error messages.

BTW, is there any broken images on the [demo site](https://skin.prinzeugen.net/) in your browser?

**Comment by prinsss** [comment] 2016-09-28 16:08
Hello there, I have already updated Blessing Skin Server to v3.1.x, which is based on a brand-new framework.

Could you make some tests of it? The problem of getting environment variables should be fixed.

Also, I separated the strings from views, and make the app able to be international. There are already 2 translations, Chinese and English. I hope that you could translate the app to Czech more easily by following these steps:
1. Copy the directory `/resources/lang/en` to `/resources/lang/crezh`
2. Add Crezh to the config array located in `/config/locales.php`
3. Now you should be able to see Crezh in the language select of every page! Switch to it!
4. Translate all strings in the directory mentioned above. After that, you will get a fully localized application!

Ah, well, the translations is not so completely. The strings in setup page and admin pages haven't been seperated, since have little time to work on it because of my test. But the pages except that ones are totally internationalized, including JavaScript files.

**Comment by prinsss** [comment] 2016-09-28 16:15
Help wanted for Crezh translations, sincerely.

Here is some tips for updating from v3.0.x:
1. Move /textures folder to /storage
2. Check the newly added variables in .env.example. If necessary, you should recopy it to .env, and modify your configurations. **Notice:** the `PWD_METHOD` must be same, orall users will get error of invalid papassword.
3. Delete /config/routes.php

Hope that you will like the new version :)

**Closed as completed** 2016-10-16 13:38 UTC
